# controllers/imports/config_form.yaml
name: Import Users
modelClass: EgerStudios\UserImport\Models\UserIMport
form: $/egerstudios/userimport/models/userimport/fields.yaml
defaultRedirect: egerstudios/userimport/userimport
