# controllers/imports/config_form.yaml
name: Import Users
modelClass: Artistro08\UserImport\Models\UserIMport
form: $/artistro08/userimport/models/userimport/fields.yaml
defaultRedirect: artistro08/userimport/userimport
