# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import Users
    modelClass: Artistro08\UserImport\Models\UserImportModel
    list: $/artistro08/userimport/models/userimportmodel/columns.yaml
    form: $/artistro08/userimport/models/userimportmodel/fields.yaml
    redirect: rainlab/user/users
